// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeV7nQcOf6aWRDMvHcCbx-RpUk4SizZJY',
    appId: '1:790130993083:web:ee6a0dc2bade2247a4869e',
    messagingSenderId: '790130993083',
    projectId: 'enviroo',
    authDomain: 'enviroo.firebaseapp.com',
    storageBucket: 'enviroo.firebasestorage.app',
    measurementId: 'G-ZWB30XLHZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2uhF_qmrAF_XwUxRrg-uw4-KmBo9FzM',
    appId: '1:790130993083:android:dd83638c867afb36a4869e',
    messagingSenderId: '790130993083',
    projectId: 'enviroo',
    storageBucket: 'enviroo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf18H8az0YD_0d4AgSZs8l9GFdzgL6vEY',
    appId: '1:790130993083:ios:a3d97a880a443e9ea4869e',
    messagingSenderId: '790130993083',
    projectId: 'enviroo',
    storageBucket: 'enviroo.firebasestorage.app',
    iosBundleId: 'com.example.enviroo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf18H8az0YD_0d4AgSZs8l9GFdzgL6vEY',
    appId: '1:790130993083:ios:a3d97a880a443e9ea4869e',
    messagingSenderId: '790130993083',
    projectId: 'enviroo',
    storageBucket: 'enviroo.firebasestorage.app',
    iosBundleId: 'com.example.enviroo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeV7nQcOf6aWRDMvHcCbx-RpUk4SizZJY',
    appId: '1:790130993083:web:d9a16c02cc4c4580a4869e',
    messagingSenderId: '790130993083',
    projectId: 'enviroo',
    authDomain: 'enviroo.firebaseapp.com',
    storageBucket: 'enviroo.firebasestorage.app',
    measurementId: 'G-HHBFR05824',
  );
}
